# Dler & Nexitally & WestData & Flower

clash_rule_base=https://raw.githubusercontent.com/SchweppesSoda/CustomRules/refs/heads/master/Clash/GeneralClashConfig.yml

#无自定义规则时防止订阅中的规则覆盖
enable_rule_generator=false

#Options for custom groups
custom_proxy_group=Proxy`select`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT
;custom_proxy_group=AutoTest`url-test`.*`http://www.gstatic.com/generate_204`600
;custom_proxy_group=Manual`select`.*

custom_proxy_group=NonChina`select`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=Telegram`select`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=YouTube`select`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=Spotify`select`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=PayPal`select`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=Microsoft`select`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=Netflix`select`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

;custom_proxy_group=GamerTW`select`[]Proxy`[]🇹🇼 TaiWan`[]Others`[]DIRECT
;custom_proxy_group=AbemaTV`select`[]Proxy`[]🇯🇵 Japan`[]Others`[]DIRECT

custom_proxy_group=Emby`select`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=TikTok`select`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=Global TV`select`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=Disney`select`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=Asian TV`select`[]DIRECT`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan

custom_proxy_group=Steam`select`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others`[]DIRECT

custom_proxy_group=Apple`select`[]DIRECT`[]Proxy`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others

custom_proxy_group=Scholar`select`[]DIRECT`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others

custom_proxy_group=Speedtest`select`[]DIRECT`[]👑 Dler-Premium`[]👑 Dler-AC`[]👑 Dler-IEPL`[]🇭🇰 Dler-HongKong`[]🇹🇼 Dler-TaiWan`[]🇸🇬 Dler-Singapore`[]🇯🇵 Dler-Japan`[]🇺🇸 Dler-UnitedStates`[]🇭🇰 Nexitally-HongKong`[]🇹🇼 Nexitally-TaiWan`[]🇸🇬 Nexitally-Singapore`[]🇯🇵 Nexitally-Japan`[]🇺🇸 Nexitally-UnitedStates`[]🇭🇰 WestData-HongKong`[]🇹🇼 WestData-TaiWan`[]🇸🇬 WestData-Singapore`[]🇯🇵 WestData-Japan`[]🇺🇸 WestData-UnitedStates`[]🇭🇰 Flower-HongKong`[]🇹🇼 Flower-TaiWan`[]🇸🇬 Flower-Singapore`[]🇯🇵 Flower-Japan`[]🇺🇸 Flower-UnitedStates`[]Others

#Dler Cloud
custom_proxy_group=👑 Dler-Premium`select`!!GROUPID=0!!(Pro|Plus|Ultra)(?!W)
custom_proxy_group=👑 Dler-AC`select`!!GROUPID=0!!(AC|Max)(?!W)
custom_proxy_group=👑 Dler-IEPL`select`!!GROUPID=0!!(IEPL)((?!Pro|Ultra).)*$
;custom_proxy_group=🇭🇰 Dler-HK-IEPL+`select`!!GROUPID=0!!(港|HK|HONG|Hong|HGC).*IEPL.*\+
custom_proxy_group=🇭🇰 Dler-HongKong`select`!!GROUPID=0!!(港|HK|HONG|Hong|HGC).(?!IEPL|AC)
; custom_proxy_group=🇲🇴 Dler-Macau`select`!!GROUPID=0!!(澳门|Macau)
custom_proxy_group=🇹🇼 Dler-TaiWan`select`!!GROUPID=0!!(台|新北|彰化|TW|Tai)
custom_proxy_group=🇸🇬 Dler-Singapore`select`!!GROUPID=0!!(新|狮城|SG|Singa).(?!IEPL|AC)
custom_proxy_group=🇯🇵 Dler-Japan`select`!!GROUPID=0!!(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
custom_proxy_group=🇺🇸 Dler-UnitedStates`select`!!GROUPID=0!!(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)

#Nexitally
custom_proxy_group=🇭🇰 Nexitally-HongKong`select`!!GROUPID=1!!(港|HK|HONG|Hong|HGC)((?!Premium).)*$
custom_proxy_group=🇹🇼 Nexitally-TaiWan`select`!!GROUPID=1!!(台|新北|彰化|TW|Tai)((?!Premium).)*$
custom_proxy_group=🇸🇬 Nexitally-Singapore`select`!!GROUPID=1!!(新|狮城|SG|Singa)((?!Premium).)*$
custom_proxy_group=🇯🇵 Nexitally-Japan`select`!!GROUPID=1!!(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)((?!Premium).)*$
custom_proxy_group=🇺🇸 Nexitally-UnitedStates`select`!!GROUPID=1!!(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|States)((?!Premium).)*$

#WestData
custom_proxy_group=🇭🇰 WestData-HongKong`select`!!GROUPID=2!!(港|HK|HONG|Hong|HGC)
custom_proxy_group=🇹🇼 WestData-TaiWan`select`!!GROUPID=2!!(台|新北|彰化|TW|Tai)
custom_proxy_group=🇸🇬 WestData-Singapore`select`!!GROUPID=2!!(新|狮城|SG|Singa)
custom_proxy_group=🇯🇵 WestData-Japan`select`!!GROUPID=2!!(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
custom_proxy_group=🇺🇸 WestData-UnitedStates`select`!!GROUPID=2!!(United States|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)

#FlowerCloud
custom_proxy_group=🇭🇰 Flower-HongKong`select`!!GROUPID=3!!(港|HK|HONG|Hong|HGC)
custom_proxy_group=🇹🇼 Flower-TaiWan`select`!!GROUPID=3!!(台|新北|彰化|TW|Tai)
custom_proxy_group=🇸🇬 Flower-Singapore`select`!!GROUPID=3!!(新|狮城|SG|Singa)
custom_proxy_group=🇯🇵 Flower-Japan`select`!!GROUPID=3!!(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
custom_proxy_group=🇺🇸 Flower-UnitedStates`select`!!GROUPID=3!!(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)

#Tag
#custom_proxy_group=🇭🇰 Tag-HongKong`select`!!GROUPID=4!!(港|HK|HONG|Hong|HGC)
#custom_proxy_group=🇹🇼 Tag-TaiWan`select`!!GROUPID=4!!(台|新北|彰化|TW|Tai)
#custom_proxy_group=🇸🇬 Tag-Singapore`select`!!GROUPID=4!!(新|狮城|SG|Singa)
#custom_proxy_group=🇯🇵 Tag-Japan`select`!!GROUPID=4!!(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
#ustom_proxy_group=🇺🇸 Tag-UnitedStates`select`!!GROUPID=4!!(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)

custom_proxy_group=Others`select`GCX`^((?!新|Jap|Tai|Singa|狮城|SG|港|HK|HONG|Hong|HGC|台|新北|彰化|TW|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣荷西|圣克拉拉|西雅图|芝加哥|US|States|Premium).)*$

custom_proxy_group=AdBlock`select`[]REJECT`[]DIRECT`[]Proxy
custom_proxy_group=Domestic`select`[]DIRECT`[]Proxy
custom_proxy_group=Final`select`[]DIRECT`[]Proxy

exclude_remarks=(剩余|到期|官网|用户|问题|临时|续费|回国|过期|游戏|流量|Gamer|Play|Traffic|Expire)

#emoji
emoji=(?i:流量|时间|应急|过期|Bandwidth|expire),🏳️‍🌈
emoji=(Emirates|阿联酋),🇦🇪
emoji=(巴基斯坦),🇵🇰
emoji=(Chile|智利),🇨🇱
emoji=(新西兰),🇳🇿
emoji=(乌克兰),🇺🇦
emoji=(摩尔多瓦),🇲🇩
emoji=(埃及),🇪🇬
emoji=(ISR|Israel|以色列),🇮🇱
#emoji=(AC|Ascension),🇦🇨
emoji=(Argentina|AR|阿根廷),🇦🇷
emoji=(Austria|奥地利|维也纳),🇦🇹
emoji=(AU|Australia|Sydney|澳大利亚|悉尼),🇦🇺
emoji=(BE|Belgium|比利时),🇧🇪
emoji=(BR|Brazil|巴西|圣保罗),🇧🇷
emoji=(Canada|加拿大|蒙特利尔|温哥华|楓葉|枫叶),🇨🇦
emoji=(Switzerland|瑞士|苏黎世),🇨🇭
emoji=(DE|Germany|法兰克福|德),🇩🇪
emoji=(Danmark|丹麦),🇩🇰
emoji=(Norway|挪威),🇳🇴
emoji=(Bulgaria|保加利亚),🇧🇬
emoji=(Hungary|匈牙利),🇭🇺
emoji=(ES|Spain|西班牙),🇪🇸
emoji=(EU|欧盟),🇪🇺
emoji=(Finland|芬兰|赫尔辛基),🇫🇮
emoji=(FR|France|法国|巴黎),🇫🇷
emoji=(?i:UK|England|United.*?Kingdom|英国|[^-]英|伦敦),🇬🇧
emoji=(?i:HK|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|[^-]港),🇭🇰
emoji=(Indonesia|印尼|印度尼西亚|雅加达),🇮🇩
emoji=(Ireland|爱尔兰|都柏林),🇮🇪
emoji=(India|印度|孟买),🇮🇳
emoji=(Italy|意大利|米兰),🇮🇹
emoji=(JP|Japan|日本|东京|大阪|埼玉|[^-]日),🇯🇵
emoji=(KP|朝鲜),🇰🇵
emoji=(KR|Korea|KOR|首尔|韩|韓),🇰🇷
emoji=(MO|Macao|澳门|CTM),🇲🇴
emoji=(MY|Malaysia|马来西亚),🇲🇾
emoji=(NL|Netherlands|荷兰|阿姆斯特丹),🇳🇱
emoji=(PH|Philippines|菲律宾),🇵🇭
emoji=(RO|罗马尼亚),🇷🇴
emoji=(RU|Russia|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|哈巴罗夫斯克|俄罗斯|[^-]俄),🇷🇺
emoji=(沙特|迪拜),🇸🇦
emoji=(SE|Sweden|瑞典),🇸🇪
emoji=(SG|Singapore|新加坡|狮城|[^-]新),🇸🇬
emoji=(TH|Thailand|泰国|曼谷),🇹🇭
emoji=(TR|Turkey|土耳其|伊斯坦布尔),🇹🇷
emoji=(?i:US|America|United.*?States|美国|[^-]美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥),🇺🇸
emoji=(VN|Vietnam|越南),🇻🇳
emoji=(Johannesburg|ZA|南非),🇿🇦
emoji=(?i:TW|Taiwan|新北|彰化|CHT|台湾|[^-]台|HINET),🇹🇼
emoji=(?i:CN|China|回国|中国|江苏|北京|上海|广州|深圳|杭州|常州|徐州|青岛|宁波|镇江|成都|back),🇨🇳
